config/routes.rb
Rails.application.routes.draw do

  get 'guest/create'
  root to: 'top#index'

  resources :users, only: %i[new create index show] do
    resources :relationships, only: %i[create destroy]
  end

  resources :restaurants do
    resource :visits, only: %i[create destroy]
  end
  resources :others_restaurants, only: %i[index show]
  resources :spots, only: %i[new index create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update new]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'top', to: 'top#index'
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'login', to: 'user_session#destroy'

  get 'terms_of_service', to: 'regulation_pages#terms_of_service'
  get 'privacy_policy', to: 'regulation_pages#privacy_policy'
  get 'inquiry', to: 'regulation_pages#inquiry'

  post 'guest', to: 'guest#create'

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :restaurants, dependent: :destroy
  has_many :active_relationship, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy
  has_many :following, through: :active_relationship, source: :followed
  has_many :passive_relationship, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followed, through: :passive_relationships, source: :following
  has_many :visits, dependent: :destroy
  has_many :visited_rst, through: :visits, source: :restaurant
  has_many :spots, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :notion, inclusion: {in: [true, false]}
  validates :introduction, length: { maximum: 250 }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  enum generation: { not_select: 0, twenties: 1, thirties: 2, forties: 3, fifties: 4, over_sixties: 5 }

  def own?(object)
    id == object.user_id
  end

  def follow(user_id)
    active_relationship.build(followed_id: user_id)
  end

  def unfollow(user_id)
    follow = self.active_relationship.find_by(user_id)
    follow.destroy
  end

  def following?(user_id)
    following.include?(user_id)
  end

  def visit(restaurant)
    visited_rst << restaurant
  end

  def unvisited(restaurant)
    visited_rst.delete(restaurant)
  end

  def visited?(restaurant)
    visited_rst.include?(restaurant)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('message.success')
      redirect_to login_url
    else
      flash.now[:error] = t('message.fault')
      render :new
    end
  end

  def index
    if params[:follow] == nil
      @users = User.all.where.not(id: current_user.id)
    elsif params[:follow] == "marked"
      @users = current_user.following.all
    end
  end

  def show
    @user = User.find(params[:id])
    @restaurants = @user.restaurants
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :generation, :password, :password_confirmation )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= render 'relationships/followed', user: user %>
  <% else %>
    <%= render 'relationships/follow', user: user %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<% content_for(:title,(t '.title')) %>
<div class="btm-space">
  <div class="flex justify-center">
    <table class="table">
      <% if @users.any? %>
        <% @users.each do |user| %>
          <tr>
            <td>
              <div class="avatar">
                <div class="rounded-full w-14 ring ring-neutral">
                  <%= image_tag user.avatar.url, alt: t('.icon') %>
                </div>
              </div>
            </td>

              <td>
                <div class="flex flex-row place-content-between">
                  <div class="font-bold text-lg"><%= user.name %></div>
                  <div class="cell text-xs"><%= user.generation_i18n %></div>
                </div>
              <p class="coment"><%= user.introduction %></p>
                  <div class="flex flex-row mt-2">
                    <%= link_to (t 'defaults.show'), user_path(user.id), class: "btn btn-secondary btn-sm btn-mid mr-1" %>
                    <div id="js-follow-button-<%= user.id %>"><%= render 'follow_button', user: user %></div>
                  </div>
              </td>
          </tr>
        <% end %>
      <% else %>
        <p><%= t('message.not_registed', item: User.model_name.human) %></p>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title,(t '.title')) %>

<div class="flex justify-center">
  <div class="form-control w-full max-w-xs media" >

  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/error_message', object: f.object %>

      <label class="label">
        <span class="label-text"><%= f.label :name %></span>
      </label>
      <%= f.text_field :name, placeholder: "nickname",  class: "input input-bordered w-full max-w-xs mb-2" %>

    <label class="label align-item">
      <span class="label-text"><%= f.label :email %></span>
    </label>
    <%= f.text_field :email, placeholder: "e@mail.com",  class: "input input-bordered w-full max-w-xs mb-2" %>

    <label class="label">
      <span class="label-text"><%= f.label :generation %></span>
    </label>
    <%= f.select :generation, User.generations_i18n.invert, {}, class: "select select-bordered w-full max-w-xs mb-2" %>

    <label class="label">
      <span class="label-text"><%= f.label :password %></span>
    </label>
    <%= f.text_field :password, placeholder: "password",  class: "input input-bordered w-full max-w-xs md-2" %>

    <label class="label">
      <span class="label-text"><%= f.label :password_confirmation %></span>
    </label>
    <%= f.text_field :password_confirmation, placeholder: "password",  class: "input input-bordered w-full max-w-xs md-2" %>

    <div class="flex justify-center mt-5">
      <%= f.submit (t 'defaults.register'), class: 'btn btn-primary btn-mid' %>
    <% end %>
    </div>
  </div>
</div>
<%= link_to (t '.to_login_page'), login_path, class: "link link-primary media flex justify-center mt-5" %>

<%= render 'shared/regulation_pages' %>
<div class="btm-space"></div>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>

<div class="flex justify-center">
  <table class="table">
    <tr>
      <td>
        <div class="avatar">
          <div class="w-24 rounded-xl ring ring-neutral">
              <%= image_tag @user.avatar.url, alt: t('.icon') %>
          </div>
        </div>
      </td>

      <td>
        <div id="js-follow-button-<%= @user.id %>"><%= render 'follow_button', user: @user %></div>
        <div class="font-bold text-lg"><%= @user.name %></div>
        <div class="text-xs"><%= @user.generation_i18n %></div>
        <div class="coment text-xs"><%= @user.introduction %></div>
      </td>
    </tr>
  </table>
</div>

  <% if @restaurants.any? %>
    <% if current_user.following?(@user) %>
      <p class="text-center font-bold mt-10 md-3">
        こっそり行ってみよう...
        <i class="fa-solid fa-user-secret"></i>
      </p>
    <% end %>

    <% @restaurants.each do |restaurant| %>
    <div class="mt-3">
      <div class="btn-place" id="js-visits-button-<%= restaurant.id %>"><%= render 'restaurants/visit_button', restaurant: restaurant %></div>
      <div><%= render 'restaurants/restaurant', restaurant: restaurant %></div>
    <% end %>
    </div>
  <% else %>
    <p class="text-center"><%= t('message.not_registed', item: 'message.not_registed', item: Restaurant.model_name.human) %></p>
  <% end %>