config/routes.rb
Rails.application.routes.draw do

  get 'guest/create'
  root to: 'top#index'

  resources :users, only: %i[new create index show] do
    resources :relationships, only: %i[create destroy]
  end

  resources :restaurants do
    resource :visits, only: %i[create destroy]
  end
  resources :others_restaurants, only: %i[index show]
  resources :spots, only: %i[new index create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update new]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'top', to: 'top#index'
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'login', to: 'user_session#destroy'

  get 'terms_of_service', to: 'regulation_pages#terms_of_service'
  get 'privacy_policy', to: 'regulation_pages#privacy_policy'
  get 'inquiry', to: 'regulation_pages#inquiry'

  post 'guest', to: 'guest#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :following_id, uniqueness: { scope: :followed_id }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :visits

  validates :rst_name, presence: true
  validates :memo, length: { maximum: 300 }

  enum rst_type: { default: 0, lunch: 1, cafe: 2, noodle: 3, dinner: 4, kannpai: 5 }

  def rst_icon
    return self.image.variant(resize: '30x30').processed
  end

end

app/models/spot.rb
class Spot < ApplicationRecord
    belongs_to :user
    geocoded_by :address
    after_validation :geocode

    validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :restaurants, dependent: :destroy
  has_many :active_relationship, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy
  has_many :following, through: :active_relationship, source: :followed
  has_many :passive_relationship, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followed, through: :passive_relationships, source: :following
  has_many :visits, dependent: :destroy
  has_many :visited_rst, through: :visits, source: :restaurant
  has_many :spots, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :notion, inclusion: {in: [true, false]}
  validates :introduction, length: { maximum: 250 }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  enum generation: { not_select: 0, twenties: 1, thirties: 2, forties: 3, fifties: 4, over_sixties: 5 }

  def own?(object)
    id == object.user_id
  end

  def follow(user_id)
    active_relationship.build(followed_id: user_id)
  end

  def unfollow(user_id)
    follow = self.active_relationship.find_by(user_id)
    follow.destroy
  end

  def following?(user_id)
    following.include?(user_id)
  end

  def visit(restaurant)
    visited_rst << restaurant
  end

  def unvisited(restaurant)
    visited_rst.delete(restaurant)
  end

  def visited?(restaurant)
    visited_rst.include?(restaurant)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :user_id, uniqueness: { scope: :restaurant_id }
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController
  skip_before_action :require_login, only: %i[create]

  def create
    guest = User.find_by(email: "guest_gets@example.com")
    auto_login(guest)
    redirect_to others_restaurants_path
    flash[:success] = t('.login_as_guest')
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]
  before_action :user_params, only: %i[update]

  def edit; end

  def update
    if guest?
      flash[:warning] = t('message.prohibit_guest', item: '更新')
      render :edit
    elsif @user.update(user_params)
      redirect_to profile_path
      flash[:success] = t('message.success')
    else
      flash.now[:warning] = t('message.fault')
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :generation, :introduction, :notion, :avatar, :avatar_cache)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def new
    @spot = Spot.new
  end

  def create
    # restaurant = current_user.restaurants.find_by(restaurant_id: params[:id])
    # @spot = Spot.restaurant.create(params[:spot_params])
    @spot = current_user.spots.new(spot_params)
    if @spot.save
      restaurant = current_user.restaurants.build(rst_name: @spot.address)
      restaurant.save
      flash[:success] = t('message.success')
      redirect_to restaurants_path
    else
      render :new
      flash[:warning] = '見つかりませんでした'
    end
  end

  def index
    #@spots = current_user.restaurants.spots
  end

  def destroy
    spot = Spot.find(params[:id])
    spot.destroy
    redirect_to :index
  end

  private

  def spot_params
    params.require(:spot).permit(:address, :latitude, :longitude, :rst_place, :user_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('message.success')
      redirect_to login_url
    else
      flash.now[:error] = t('message.fault')
      render :new
    end
  end

  def index
    if params[:follow] == nil
      @users = User.all.where.not(id: current_user.id)
    elsif params[:follow] == "marked"
      @users = current_user.following.all
    end
  end

  def show
    @user = User.find(params[:id])
    @restaurants = @user.restaurants
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :generation, :password, :password_confirmation )
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    current_user.visit(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    current_user.unvisited(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = "がらぽんごはん"

    page_title.empty? ? base_title : base_title + ' | ' + page_title
  end
end

app/helpers/guest_helper.rb
module GuestHelper

  def guest?
    User.find_by(email: current_user.email) == User.find_by(email: "guest_gets@example.com")
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error shadow-lg media">
    <div>
      <ul style="list-style: disc;">
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> shadow-lg media">
    <span><%= message %></span>
  </div>
<% end %>

<!-- Theses below are supporting dynamic construction for daisyUI-->
<!-- alert-warning alert-success alert-info -->

app/views/shared/_footer.html.erb
<footer>
  <div class="media-smh btm-nav btm-nav-lg">
    <%= link_to new_restaurant_path do %>
      <i class="fa-solid fa-pen-to-square"></i>
      <p class="text-xs"><%= (t 'footer.memo') %></p>
    <% end %>
    <%= link_to users_path do %>
      <i class="fa-solid fa-children"></i>
      <p class="text-xs"><%= (t 'footer.user') %></p>
    <% end %>
    <%= link_to users_path(follow: "marked") do %>
      <i class="fa-solid fa-user-secret"></i>
      <p class="text-xs"><%= (t 'footer.follow') %></p>
    <% end %>
    <%= link_to profile_path do %>
      <i class="fa-solid fa-circle-user"></i>
      <p class="text-xs"><%= (t 'footer.profile') %></p>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="col-right"></div>
<div class="col-left"></div>

<div class="justify-evenly sticky top-0 head-z h-center">
  <div class="bg-base-100">
      <p class="font-xs"><%= link_to (t 'defaults.title') %><p>
    <div class="flex h-center">
      <div class="flex-row mb-5">
        <%= link_to (t 'defaults.restaurants_list'), others_restaurants_path, class: "btn btn-sm btn-primary mr-0.5 text-xs" %>
        <%= link_to (t 'defaults.my_list'), restaurants_path, class: "btn btn-sm btn-primary mr-0.5 text-xs" %>

      <%= link_to new_restaurant_path do %>
        <div class="btn btn-sm btn-primary mr-0.5 text-xs media-smh-head">
          <i class="fa-solid fa-pen-to-square mr-1"></i>
          <p class="text-xs"><%= (t 'footer.memo') %></p>
        </div>
      <% end %>

        <%= link_to users_path do %>
          <div class="btn btn-sm btn-primary mr-0.5 text-xs media-smh-head">
            <i class="fa-solid fa-children mr-1"></i>
            <p class="text-xs"><%= (t 'footer.user') %></p>
          </div>
        <% end %>

        <%= link_to users_path(follow: "marked") do %>
          <div class="btn btn-sm btn-primary mr-0.5 text-xs media-smh-head">
            <i class="fa-solid fa-user-secret mr-1"></i>
            <p class="text-xs"><%= (t 'footer.follow') %></p>
          </div>
        <% end %>

        <%= link_to profile_path do %>
          <div class="btn btn-sm btn-primary mr-0.5 text-xs media-smh-head">
            <i class="fa-solid fa-circle-user mr-1"></i>
            <p class="text-xs"><%= (t 'footer.profile') %></p>
          </div>
        <% end %>

      <%= link_to login_path, method: :delete do %>
        <div class="btn btn-sm btn-primary mr-0.5 text-xs">
          <i class="fa-solid fa-right-from-bracket mr-1"></i>
          <p><%= (t 'defaults.logout') %></p>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_pre_login_footer.html.erb
<footer>
  <div class="btn-disabled">
    <div class="btm-nav btm-nav-lg media">
      <%= link_to new_restaurant_path do %>
        <i class="fa-solid fa-pen-to-square"></i>
        <p class="text-xs"><%= (t 'footer.memo') %></p>
      <% end %>
      <%= link_to users_path do %>
        <i class="fa-solid fa-children"></i>
        <p class="text-xs"><%= (t 'footer.user') %></p>
      <% end %>
      <%= link_to users_path(follow: "marked") do %>
        <i class="fa-solid fa-user-secret"></i>
        <p class="text-xs"><%= (t 'footer.follow') %></p>
      <% end %>
      <%= link_to profile_path do %>
        <i class="fa-solid fa-circle-user"></i>
        <p class="text-xs"><%= (t 'footer.profile') %></p>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_pre_login_header.html.erb
<div class="col-right"></div>
<div class="col-left"></div>

<div class="justify-evenly media sticky top-0 head-z">
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <p class="font-sm"><%= link_to (t 'defaults.title'), top_path, class: "btn btn-ghost normal-case" %></p>
    </div>

      <div class="navbar-end">
        <%= link_to (t 'defaults.restaurants_list'), others_restaurants_path, class: "btn btn-sm btn-primary mr-0.5 text-xs" %>
        <%= link_to (t 'defaults.my_list'), '#', class: "btn btn-sm btn-disabled mr-0.5 text-xs" %>
        <%= link_to login_path do %>
          <i class="fa-solid fa-right-to-bracket"></i>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_regulation_pages.html.erb
<div class="media regulation text-sm">
  <div class="flex justify-evenly">
    <div><%= link_to (t 'regulation_pages.terms_of_service.title'), terms_of_service_path, class: "link link-hover" %></div>
    <div><%= link_to (t 'regulation_pages.privacy_policy.title'), privacy_policy_path, class: "link link-hover" %></div>
    <div><%= link_to (t 'regulation_pages.inquiry.title'), inquiry_path, class: "link link-hover" %></div>
  </div>
  <p class="flex justify-center mt-1">Copyright © 2023 がらぽんごはん</p>
</div>

app/views/shared/_search_form.html.erb
<div class="sm:flex justify-center mt-2 ml-5 media">
  <%= search_form_for q, url: url do |f| %>
    <%= f.search_field :rst_name_cont, placeholder: (t 'defaults.search'), class: "input input-bordered input-xs max-w-xs" %>
    <button class="btn btn-square btn-xs btn-outline">
      <% f.submit %>
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  <% end %>
</div>