config/routes.rb
Rails.application.routes.draw do

  get 'guest/create'
  root to: 'top#index'

  resources :users, only: %i[new create index show] do
    resources :relationships, only: %i[create destroy]
  end

  resources :restaurants do
    resource :visits, only: %i[create destroy]
  end
  resources :others_restaurants, only: %i[index show]
  resources :spots, only: %i[new index create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[create edit update new]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'top', to: 'top#index'
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'login', to: 'user_session#destroy'

  get 'terms_of_service', to: 'regulation_pages#terms_of_service'
  get 'privacy_policy', to: 'regulation_pages#privacy_policy'
  get 'inquiry', to: 'regulation_pages#inquiry'

  post 'guest', to: 'guest#create'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :visits

  validates :rst_name, presence: true
  validates :memo, length: { maximum: 300 }

  enum rst_type: { default: 0, lunch: 1, cafe: 2, noodle: 3, dinner: 4, kannpai: 5 }

  def rst_icon
    return self.image.variant(resize: '30x30').processed
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[edit update destroy]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
      flash[:info] = t('message.success')
    else
      flash.now[:warning] = t('message.fault')
      render :new
    end
  end

  def index
    @restaurant = Restaurant.new
    @my_list = current_user.restaurants.includes(:user).ransack(params[:q])
    @restaurants = @my_list.result(distinct: true).order(created_at: "DESC")
    @random_select = @restaurants.shuffle.first
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @user = @restaurant.user
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(params[:id])
      flash[:success] = t('message.updated')
    else
      flash.now[:error] = t('message.fault')
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
    flash[:success] = t('.success')
  end

  private

  def set_restaurant
    @restaurant = current_user.restaurants.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:rst_name, :rst_type, :place, :feature, :memo)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_random_select.html.erb
<div class="md:flex justify-center ml-5 media">
  <button class="btn btn-active btn-secondary btn-wide mt-2 mb-7" id="js-btn">
    <%= t('.random') %>
  </button>
</div>

<div id="modal" class="modal">
  <div class="modal-content">
    <div class="modal-body">
        <div class="garagara-result fadeUp" >
          <% if @random_select %>
              <p class="font-sm"><%= t('.how_is_this?') %></p>
              <p class="font-sm"><%= "〜  #{ @random_select.rst_name }  〜" %></p>
          <% else %>
            <%= t('message.not_registed', item: Restaurant.model_name.human) %>
          <% end %>
        </div>
            <div class="modal-close-btn flex justify-center">
              <button id="closeBtn" class="btn btn-secondary btn-mid btn-outline">
                <%= t('.close') %>
              </button>
              <% if @random_select %>
                <button id="closeBtn" class="btn btn-secondary btn-mid btn-outline">
                  <%= link_to (t 'defaults.show'), restaurant_path(@random_select.id) %>
                </button>
              <% end %>
            </div>
      <div class="flex justify-center" >
        <%= video_tag "garagara.mp4", autoplay: true, muted: true %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_restaurant.html.erb
<div class="flex justify-center">
  <table class="table table-fixed border-dashed border-b border-primary-focus">
      <tr data-href="<%= restaurant_path(restaurant.id) %>">
        <td>
          <div class="flex items-center">
            <div class="avatar">
              <div class="w-12 rounded-xl">
                <% if restaurant.rst_type %>
                  <%= image_tag "#{restaurant.rst_type}.png", alt: t('default.picture') %>
                <% else %>
                  <%= image_tag "default.png", alt: t('default.picture') %>
                <% end %>
              </div>
            </div>
          </div>
        </td>

        <td>
          <div class="text-xs opacity-90 mb-1 mr-0 max_11"><%= restaurant.place %></div>
          <div class="font-bold text-lg mb-1 max_11"><%= restaurant.rst_name %></div>
          <span class="badge badge-ghost badge-sm mb-2 max_11">
            <%= restaurant.feature %>
          </span>
            <p class="text-xs max_11">
            <i class="fa-solid fa-pencil">.</i>
            <%= restaurant.memo %></p>
        </td>


        <td>
          <div class="btn btn-outline">
            <% if logged_in? && current_user.own?(restaurant) %>
              <%= link_to (t 'defaults.show'), restaurant_path(restaurant.id) %>
            <% else %>
              <%= link_to (t 'defaults.show'), others_restaurant_path(restaurant.id) %>
            <% end %>
          </div>
        </td>
      </tr>
  </table>
</div>

app/views/restaurants/_small_new.html.erb
<div class="flex justify-center">
  <table class="table table-fixed border-dashed border-b border-primary-focus">
    <%= form_with model: @restaurant, url: { controller: 'restaurants', action: 'create'} do |f| %>
      <%= render 'shared/error_message', object: f.object %>
        <tr>
          <td>
            <div class="flex items-center">
              <div class="avatar">
                <div class="w-12 rounded-xl">
                  <%= image_tag "default.png", alt: t('default.picture') %>
                </div>
              </div>
            </div>
          </td>

          <td>
            <%= f.text_field :place, placeholder: t('restaurants.new.place'), class: "input input-bordered input-xs max-w-xs opacity-90 md-5"%>
            <div class="">
              <%= f.text_field :rst_name, placeholder: t('restaurants.new.rst_name'), class: "input input-bordered input-sm max-w-xs"%>
            </div>
            <%= f.text_field :memo, placeholder: t('restaurants.new.memo'), class: "input input-bordered input-sm max-w-xs"%>
          </td>
          <td><%= f.submit (t 'defaults.register'), class: 'btn btn-primary' %></td>
        </tr>
      </div>
    <% end %>
  </table>
</div>

app/views/restaurants/_visit_button.html.erb
<% if current_user.following?(@user) %>
  <% if current_user.visited?(restaurant) %>
    <%= render 'visits/visit', { restaurant: restaurant } %>
  <% else %>
    <%= render 'visits/unvisited', { restaurant: restaurant } %>
  <% end %>
<% end %>

app/views/restaurants/edit.html.erb
<% content_for(:title, (t '.title', item: @restaurant.rst_name)) %>
<div class="flex justify-center">
  <%= form_with model: @restaurant, local: true do |f| %>
    <%= render 'shared/error_message', object: f.object %>

    <div class="icon_check mt-10 mb-5">
      <% Restaurant.rst_types.each do |key, value| %>
        <div class="btn btn-circle btn-ghost mx-1 mb-5">
          <div class="w-24 rounded ring-2 hover:ring-4 ring-neutral">
            <%= f.radio_button :rst_type, key, class: "radio radio-primary" %>
              <%= image_tag "#{key}.png", :size =>'50x50', alt: t('default.picture') %>
          </div>
        </div>
      <% end %>
      </div>
  </div>

    <div class="flex w-full mb-1 justify-center">
      <%= f.label :rst_name, class: "m-2" %>
      <%= f.text_field :rst_name, class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1 justify-center">
      <%= f.label :place, class: "m-2" %>
      <%= f.text_field :place, class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :feature, class: "m-2" %>
      <%= f.text_field :feature, class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :memo, class: "m-2 text-sm memo" %>
      <%= f.text_area :memo, class: "textarea textarea-bordered input-sm max-w-xs w-full" %><br>
    </div>

    <div class="flex justify-center mt-5" >
      <%= f.submit (t 'defaults.update'), class: 'btn btn-secondary btn-wide' %>
    </div>
  <% end %>

app/views/restaurants/index.html.erb
<%= content_for(:title, (t '.title')) %>
  <%= render 'shared/search_form', q: @my_list, url: restaurants_path %>
  <%= render 'random_select' %>
    <% if @restaurants.any? %>
      <%= render 'small_new' %>
      <div class="btm-space"><%= render @restaurants %></div>
    <% else %>
      <p class="text-center"><%= t('.not_have_lists') %></p>
      <%= render 'small_new' %>
    <% end %>

    <%= javascript_pack_tag 'random_select' %>

app/views/restaurants/new.html.erb
<% content_for(:title, (t '.title')) %>
<div class="flex justify-center my-10" >
  <div  class="btn btn-wide btn-secondary" >
    <%= link_to 'マップから探す', new_spot_path %>
    &emsp;
    <i class="fa-solid fa-map-location-dot"></i>
  </div>
</div>

<div class="border-dashed border-b-2 border-base-400"></div>

<div class="flex justify-center" >
  <%= form_with model: @restaurant, local: true do |f| %>
    <%= render 'shared/error_message', object: f.object %>

      <div class="icon_check my-10">
        <% Restaurant.rst_types.each do |key, value| %>
          <div class="btn btn-circle btn-ghost mx-1 mb-3">
            <div class="w-24 rounded ring-2 hover:ring-4 ring-neutral">
              <%= f.radio_button :rst_type, key, class: "radio radio-primary" %>
              <%= image_tag "#{key}.png",:size =>'50x50', alt: t('default.picture') %>
            </div>
          </div>
        <% end %>
      </div>
</div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :rst_name, class: "m-2" %>
      <%= f.text_field :rst_name, placeholder: t('.rst_name'), class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :place, class: "m-2" %>
      <%= f.text_field :place, placeholder: t('.place'), class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :feature, class: "m-2" %>
      <%= f.text_field :feature, placeholder: t('.feature'),  class: "input input-bordered max-w-xs w-full" %><br>
    </div>

    <div class="flex w-full mb-1.5 justify-center">
      <%= f.label :memo, class: "m-2 text-sm memo" %>
      <%= f.text_area :memo, placeholder: t('.memo'),  class: "textarea textarea-bordered input-sm w-full max-w-xs" %><br>
    </div>

    <div class="flex justify-center mt-5" >
      <%= f.submit (t 'defaults.register'), class: 'btn btn-wide btn-primary' %>
    </div>
  <% end %>

<div class="btm-space"></div>

app/views/restaurants/show.html.erb
<% content_for(:title, @restaurant.rst_name) %>
<div class="flex justify-center flex-wrap mt-10 mb-7">
  <div class="avatar">
    <div class="w-24 rounded-xl">
        <%= image_tag ("#{@restaurant.rst_type}.png") %>
      </div>
    </div>
  </div>
    <div class="flex w-full mb-1 justify-center">
        <%= @restaurant.place %>
    </div>
    <div class="flex w-full mb-5 justify-center">
        <%= @restaurant.rst_name %>
    </div>
    <div class="flex w-full mb-5 justify-center">
        <%= @restaurant.feature %>
    </div>
    <div class="flex w-full mb-10 justify-center">
        <div class="rst-memo"><%= @restaurant.memo %></div>
    </div>

  <div class="flex justify-center flex-wrap" >
    <% if logged_in? && current_user.own?(@restaurant) %>
      <%= link_to (t 'defaults.edit'), edit_restaurant_path(@restaurant.id), class: "btn btn-primary m-2" %>
      <%= button_to (t '.delete'), restaurant_path(@restaurant.id), method: :delete, class: "btn btn-accent m-2" %>
    <% end %>
  </div>